// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6xOqxAlfE6LZvDV3So0tr9hRDaBy_L8',
    appId: '1:140712549298:web:ff3fbfcc0c187a1af462ab',
    messagingSenderId: '140712549298',
    projectId: 'task-mate-fc0a6',
    authDomain: 'task-mate-fc0a6.firebaseapp.com',
    storageBucket: 'task-mate-fc0a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfjlBlstb9CxpbucrvjebA4KsxTbRLLA',
    appId: '1:140712549298:android:7793706c6ce62533f462ab',
    messagingSenderId: '140712549298',
    projectId: 'task-mate-fc0a6',
    storageBucket: 'task-mate-fc0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkONhwbEKFm0PytwkEdT5zMc2Gde3kVXE',
    appId: '1:140712549298:ios:c507780602f8baadf462ab',
    messagingSenderId: '140712549298',
    projectId: 'task-mate-fc0a6',
    storageBucket: 'task-mate-fc0a6.firebasestorage.app',
    iosBundleId: 'com.example.notify',
  );

}